# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
# workflows:
#   # Name the workflow "welcome"
#   welcome:
#     # Run the welcome/run job in its own container
#     jobs:
#       - welcome/run
jobs:
  build:
    docker:
      - image: circleci/elixir:1.11.2
    environment:
      MIX_ENV: test

    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
        key: deps-cache-{{ checksum "mix.lock" }}
      - run: mix do deps.get, deps.compile
      - save_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
          paths:
              - deps
              - ~/.mix
              - _build
      
      - run: mix compile

      - run: echo "$OPT_VERSION $ELIXIR_VERSION" > .version_file
      - restore_cache:
          keys:
              - plt-cache-{{ checksum ".version-file" }}-{{ checksum "mix.lock "}}
      - run: mix dialyzer --plt
      - save_cache:
        key: plt-cache-{{ checksum ".version_file"  }}-{{ checksum "mix.lock" }}
        paths:
            - _build
            - deps
            - ~/.mix
test:
  docker:
    - image: circleci/elixir:1.11.2
  steps:
    - checkout
    - restore_cache:
        key: deps-cache-{{ checksum "mix.lock" }}
    - run: mix coveralls.html

    - store_artifacts:
        path: cover
        destination: coverage_results

generate_documentation:
  docker:
    - image: circleci/elixir:1.11.2
  environment:
    MIX_ENV: test

  steps:
    - checkout
    - restore_cache:
        key: deps-cache-{{ checksum "mix.lock" }}
    - run: mix docs

    - store_artifacts:
        path: doc
        destiation: documentation

dializer:
  docker:
    - image: circleci/elixir:1.11.2
  environment:
    MIX_ENV: test
  
  steps:
    - checkout
    - run: echo "$OTP_VERSION $ELIXIR_VERSION" > .version_file
    - restore_cache:
        keys:
            - plt-cache-{{ checksum ".version_file" }}-{{ checksum "mix.lock" }}
    - run: mix dialyzer --halt-exit-status

format_check:
  docker:
    - image: circleci/elixir:1.11
  environment:
    MIX_ENV: test
  
  steps:
    - checkout

    - run: mix format --check-formatted

workflows:
  build_and_test:
    jobs:
      - build
      - format_check:
          requires:
              - build
      - generate_documentation:
          requires:
              - build
      - dialyzer:
          require:
              - build
      - test:
          require:
              -build
      